# Generated by Django 3.1.1 on 2020-09-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Имя и фамилия')),
                ('email', models.EmailField(max_length=100, verbose_name='Почта')),
                ('password', models.CharField(max_length=100, unique=True, verbose_name='Пароль')),
                ('confirm_password', models.CharField(max_length=100, unique=True, verbose_name='Потвердить пароль')),
            ],
            options={
                'verbose_name': 'Подписчик',
                'verbose_name_plural': 'Подписчики',
                'ordering': ['name'],
            },
        ),
    ]
